language: python
python:
  - "2.7"
env:
  - DJANGO=1.6
  - DJANGO=1.7
  - DJANGO=1.8
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -r requirements/prod.txt --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - pip install coveralls
before_script:
  - "pep8 --exclude=migrations paiji2"
  - pyflakes -x W paiji2
script:
  - coverage run --source=paiji2 manage.py test
after_success:
  - coveralls
